variables:
  # GIT_CLEAN_FLAGS: none # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4154
  GIT_CLONE_PATH: $CI_BUILDS_DIR/isbd-emulator # https://stackoverflow.com/questions/64089704/gitlab-runner-change-builds-dir
  # GIT_SUBMODULE_STRATEGY: recursive # https://docs.gitlab.com/ee/ci/git_submodules.html#use-git-submodules-in-cicd-jobs

# ! Is important to allow CI_JOB_TOKEN in the private submodules referenced from this project: 
# https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#add-a-project-to-the-inbound-job-token-scope-allowlist

stages:
  - test

test:
  stage: test
  timeout: 1 minutes
  script:
    - npm run build
    - npm run test
  tags:
    - isbd-emulator
  only:
    - dev
    - main