default:
  image: node:latest
  tags:
    - moon
    - docker

cache:
  paths:
    - build/
    - node_modules/

build-job:
  script:
    - npm i
  only:
    - dev

test-job:
  script:
    - npm run test
  only:
    - dev